# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



import subprocess
import mysql.connector
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 110, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 160, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Usernamelabel = QtWidgets.QLineEdit(self.centralwidget)
        self.Usernamelabel.setGeometry(QtCore.QRect(350, 110, 171, 22))
        self.Usernamelabel.setObjectName("Usernamelabel")
        self.passwordlabel = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordlabel.setGeometry(QtCore.QRect(350, 160, 171, 22))
        self.passwordlabel.setObjectName("passwordlabel")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(130, 200, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(280, 290, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.usertype = QtWidgets.QLineEdit(self.centralwidget)
        self.usertype.setGeometry(QtCore.QRect(350, 210, 171, 22))
        self.usertype.setObjectName("usertype")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)



        #button connection
        self.pushButton.clicked.connect(self.inputnew)

        self.conn = mysql.connector.connect(
            host='localhost',
            user='root',
            password='Aaravm123!',
            database='pro'  
        )
        self.cursor = self.conn.cursor()
        print('Connection established')      


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Enter new Username"))
        self.label_2.setText(_translate("MainWindow", "Enter Password"))
        self.label_3.setText(_translate("MainWindow", "Enter User type (U or S)"))
        self.pushButton.setText(_translate("MainWindow", "Enter"))


    def inputnew(self):
            entered_username = self.Usernamelabel.text()
            entered_password = self.passwordlabel.text()
            entered_choice = self.usertype.text()

            print(entered_username)
            print(entered_password)
            print(entered_choice)

            try:
                self.cursor.execute("SELECT max(id) from login")
                result = self.cursor.fetchone()

                if result[0] is not None:
                    new_id = int(result[0]) + 1
                else:
                    new_id = 1
    
                print('Query executed')
                self.cursor.execute("INSERT INTO login (id, username, user_password, usertype) VALUES (%s, %s, %s, %s)", (new_id, entered_username, entered_password, entered_choice))
                self.conn.commit()
                print('Entered successfully')

            except mysql.connector.Error as e:
                print("Error:", e)

           


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
